### ISSUE TITLE
can I use this monorepo for my production application? 

### ISSUE THREAD

**Issue by vndpal** [francislagares/mern-monorepo#1]
This is really awesome boilerplate structure. I am planning to develop a application that is going to be on production. I am fairly new to MERN stack and I am wondering if I can follow this monorepo boilerplate for my application. Also please let me know if this is industry standard for creating a MERN monorepo. 
This is just an inquiry so feel free to close this issue.

**Comment by francislagares** [comment]
Sure you can use this monorepo for your application, just keep in mind that dependencies hasn't been updated for a while.
Actually I'm planning to do some upgrades and refactor backend folder structure and replace jest with vitest, and some more.
I also would suggest to take a look at some tools like Nx to setup monorepos.

**Comment by VNDPAL** [comment]
Awesome work man! I'll go with what you currently have here but I'll keep an eye on this repo.
